swagger: '2.0'
info:
    title: Swagger
    description: Swagger API sample
    version: 1.0.0
basePath: /api
paths:
    /swagger:
        get:
            summary: Swagger
            responses:
                200:
                    description: Swagger
